/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/conversation/[conversationSlugId]/edit/': RouteRecordInfo<
      '/conversation/[conversationSlugId]/edit/',
      '/conversation/:conversationSlugId/edit',
      { conversationSlugId: ParamValue<true> },
      { conversationSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[conversationSlugId]/edit/survey/': RouteRecordInfo<
      '/conversation/[conversationSlugId]/edit/survey/',
      '/conversation/:conversationSlugId/edit/survey',
      { conversationSlugId: ParamValue<true> },
      { conversationSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[conversationSlugId]/export': RouteRecordInfo<
      '/conversation/[conversationSlugId]/export',
      '/conversation/:conversationSlugId/export',
      { conversationSlugId: ParamValue<true> },
      { conversationSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[conversationSlugId]/export.[exportId]': RouteRecordInfo<
      '/conversation/[conversationSlugId]/export.[exportId]',
      '/conversation/:conversationSlugId/export/:exportId',
      { conversationSlugId: ParamValue<true>, exportId: ParamValue<true> },
      { conversationSlugId: ParamValue<false>, exportId: ParamValue<false> },
      | never
    >,
    '/conversation/[conversationSlugId]/report': RouteRecordInfo<
      '/conversation/[conversationSlugId]/report',
      '/conversation/:conversationSlugId/report',
      { conversationSlugId: ParamValue<true> },
      { conversationSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId]': RouteRecordInfo<
      '/conversation/[postSlugId]',
      '/conversation/:postSlugId',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | '/conversation/[postSlugId]/'
      | '/conversation/[postSlugId]/analysis'
    >,
    '/conversation/[postSlugId]/': RouteRecordInfo<
      '/conversation/[postSlugId]/',
      '/conversation/:postSlugId',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId]/analysis': RouteRecordInfo<
      '/conversation/[postSlugId]/analysis',
      '/conversation/:postSlugId/analysis',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].embed': RouteRecordInfo<
      '/conversation/[postSlugId].embed',
      '/conversation/:postSlugId/embed',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | '/conversation/[postSlugId].embed/'
      | '/conversation/[postSlugId].embed/analysis'
    >,
    '/conversation/[postSlugId].embed/': RouteRecordInfo<
      '/conversation/[postSlugId].embed/',
      '/conversation/:postSlugId/embed',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].embed/analysis': RouteRecordInfo<
      '/conversation/[postSlugId].embed/analysis',
      '/conversation/:postSlugId/embed/analysis',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding',
      '/conversation/:postSlugId/onboarding',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | '/conversation/[postSlugId].onboarding/'
      | '/conversation/[postSlugId].onboarding/complete'
      | '/conversation/[postSlugId].onboarding/question.[questionSlugId]'
      | '/conversation/[postSlugId].onboarding/summary'
      | '/conversation/[postSlugId].onboarding/verify'
      | '/conversation/[postSlugId].onboarding/verify/email'
      | '/conversation/[postSlugId].onboarding/verify/email-code'
      | '/conversation/[postSlugId].onboarding/verify/hard'
      | '/conversation/[postSlugId].onboarding/verify/identity'
      | '/conversation/[postSlugId].onboarding/verify/passport'
      | '/conversation/[postSlugId].onboarding/verify/phone'
      | '/conversation/[postSlugId].onboarding/verify/phone-code'
      | '/conversation/[postSlugId].onboarding/verify/ticket'
    >,
    '/conversation/[postSlugId].onboarding/': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/',
      '/conversation/:postSlugId/onboarding',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/complete': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/complete',
      '/conversation/:postSlugId/onboarding/complete',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/question.[questionSlugId]': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/question.[questionSlugId]',
      '/conversation/:postSlugId/onboarding/question/:questionSlugId',
      { postSlugId: ParamValue<true>, questionSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false>, questionSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/summary': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/summary',
      '/conversation/:postSlugId/onboarding/summary',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/verify': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify',
      '/conversation/:postSlugId/onboarding/verify',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | '/conversation/[postSlugId].onboarding/verify/email'
      | '/conversation/[postSlugId].onboarding/verify/email-code'
      | '/conversation/[postSlugId].onboarding/verify/hard'
      | '/conversation/[postSlugId].onboarding/verify/identity'
      | '/conversation/[postSlugId].onboarding/verify/passport'
      | '/conversation/[postSlugId].onboarding/verify/phone'
      | '/conversation/[postSlugId].onboarding/verify/phone-code'
      | '/conversation/[postSlugId].onboarding/verify/ticket'
    >,
    '/conversation/[postSlugId].onboarding/verify/email': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify/email',
      '/conversation/:postSlugId/onboarding/verify/email',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/verify/email-code': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify/email-code',
      '/conversation/:postSlugId/onboarding/verify/email-code',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/verify/hard': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify/hard',
      '/conversation/:postSlugId/onboarding/verify/hard',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/verify/identity': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify/identity',
      '/conversation/:postSlugId/onboarding/verify/identity',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/verify/passport': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify/passport',
      '/conversation/:postSlugId/onboarding/verify/passport',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/verify/phone': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify/phone',
      '/conversation/:postSlugId/onboarding/verify/phone',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/verify/phone-code': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify/phone-code',
      '/conversation/:postSlugId/onboarding/verify/phone-code',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/[postSlugId].onboarding/verify/ticket': RouteRecordInfo<
      '/conversation/[postSlugId].onboarding/verify/ticket',
      '/conversation/:postSlugId/onboarding/verify/ticket',
      { postSlugId: ParamValue<true> },
      { postSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/import/[importSlugId]': RouteRecordInfo<
      '/conversation/import/[importSlugId]',
      '/conversation/import/:importSlugId',
      { importSlugId: ParamValue<true> },
      { importSlugId: ParamValue<false> },
      | never
    >,
    '/conversation/new/create/': RouteRecordInfo<
      '/conversation/new/create/',
      '/conversation/new/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/conversation/new/review/': RouteRecordInfo<
      '/conversation/new/review/',
      '/conversation/new/review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/conversation/new/seed/': RouteRecordInfo<
      '/conversation/new/seed/',
      '/conversation/new/seed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/conversation/new/survey/': RouteRecordInfo<
      '/conversation/new/survey/',
      '/conversation/new/survey',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/analysis-report-test': RouteRecordInfo<
      '/dev/analysis-report-test',
      '/dev/analysis-report-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/component-testing': RouteRecordInfo<
      '/dev/component-testing',
      '/dev/component-testing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/opinion-group-visualization': RouteRecordInfo<
      '/dev/opinion-group-visualization',
      '/dev/opinion-group-visualization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/test-components/AnalysisReportTest': RouteRecordInfo<
      '/dev/test-components/AnalysisReportTest',
      '/dev/test-components/AnalysisReportTest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/test-components/AsyncStateHandlerTest': RouteRecordInfo<
      '/dev/test-components/AsyncStateHandlerTest',
      '/dev/test-components/AsyncStateHandlerTest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/test-components/EmbeddedBrowserWarningTest': RouteRecordInfo<
      '/dev/test-components/EmbeddedBrowserWarningTest',
      '/dev/test-components/EmbeddedBrowserWarningTest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/test-components/OpinionGroupVisualizationTest': RouteRecordInfo<
      '/dev/test-components/OpinionGroupVisualizationTest',
      '/dev/test-components/OpinionGroupVisualizationTest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/test-components/PreferencesDialogTest': RouteRecordInfo<
      '/dev/test-components/PreferencesDialogTest',
      '/dev/test-components/PreferencesDialogTest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/guidelines/': RouteRecordInfo<
      '/legal/guidelines/',
      '/legal/guidelines',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/privacy/': RouteRecordInfo<
      '/legal/privacy/',
      '/legal/privacy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal/terms/': RouteRecordInfo<
      '/legal/terms/',
      '/legal/terms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moderate/conversation/[conversationSlugId]/': RouteRecordInfo<
      '/moderate/conversation/[conversationSlugId]/',
      '/moderate/conversation/:conversationSlugId',
      { conversationSlugId: ParamValue<true> },
      { conversationSlugId: ParamValue<false> },
      | never
    >,
    '/moderate/conversation/[conversationSlugId]/opinion/[opinionSlugId]/': RouteRecordInfo<
      '/moderate/conversation/[conversationSlugId]/opinion/[opinionSlugId]/',
      '/moderate/conversation/:conversationSlugId/opinion/:opinionSlugId',
      { conversationSlugId: ParamValue<true>, opinionSlugId: ParamValue<true> },
      { conversationSlugId: ParamValue<false>, opinionSlugId: ParamValue<false> },
      | never
    >,
    '/notification/': RouteRecordInfo<
      '/notification/',
      '/notification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step1-login/': RouteRecordInfo<
      '/onboarding/step1-login/',
      '/onboarding/step1-login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step1-signup/': RouteRecordInfo<
      '/onboarding/step1-signup/',
      '/onboarding/step1-signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step2-signup/': RouteRecordInfo<
      '/onboarding/step2-signup/',
      '/onboarding/step2-signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step3-email-1/': RouteRecordInfo<
      '/onboarding/step3-email-1/',
      '/onboarding/step3-email-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step3-email-2/': RouteRecordInfo<
      '/onboarding/step3-email-2/',
      '/onboarding/step3-email-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step3-passport/': RouteRecordInfo<
      '/onboarding/step3-passport/',
      '/onboarding/step3-passport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step3-phone-1/': RouteRecordInfo<
      '/onboarding/step3-phone-1/',
      '/onboarding/step3-phone-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step3-phone-2/': RouteRecordInfo<
      '/onboarding/step3-phone-2/',
      '/onboarding/step3-phone-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/step4-username/': RouteRecordInfo<
      '/onboarding/step4-username/',
      '/onboarding/step4-username',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/[reportType]/[conversationSlugId]/[[opinionSlugId]]': RouteRecordInfo<
      '/reports/[reportType]/[conversationSlugId]/[[opinionSlugId]]',
      '/reports/:reportType/:conversationSlugId/:opinionSlugId?',
      { reportType: ParamValue<true>, conversationSlugId: ParamValue<true>, opinionSlugId?: ParamValueZeroOrOne<true> },
      { reportType: ParamValue<false>, conversationSlugId: ParamValue<false>, opinionSlugId?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/administrator/organization/': RouteRecordInfo<
      '/settings/account/administrator/organization/',
      '/settings/account/administrator/organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/content-preference/': RouteRecordInfo<
      '/settings/account/content-preference/',
      '/settings/account/content-preference',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/profile/': RouteRecordInfo<
      '/settings/account/profile/',
      '/settings/account/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/languages/': RouteRecordInfo<
      '/settings/languages/',
      '/settings/languages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/languages/display-language/': RouteRecordInfo<
      '/settings/languages/display-language/',
      '/settings/languages/display-language',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/languages/spoken-languages/': RouteRecordInfo<
      '/settings/languages/spoken-languages/',
      '/settings/languages/spoken-languages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/verification-status/': RouteRecordInfo<
      '/settings/verification-status/',
      '/settings/verification-status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/topic/[topicCode]': RouteRecordInfo<
      '/topic/[topicCode]',
      '/topic/:topicCode',
      { topicCode: ParamValue<true> },
      { topicCode: ParamValue<false> },
      | never
    >,
    '/topics/': RouteRecordInfo<
      '/topics/',
      '/topics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user-profile': RouteRecordInfo<
      '/user-profile',
      '/user-profile',
      Record<never, never>,
      Record<never, never>,
      | '/user-profile/conversations/'
      | '/user-profile/opinions/'
    >,
    '/user-profile/conversations/': RouteRecordInfo<
      '/user-profile/conversations/',
      '/user-profile/conversations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user-profile/opinions/': RouteRecordInfo<
      '/user-profile/opinions/',
      '/user-profile/opinions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verify/email/': RouteRecordInfo<
      '/verify/email/',
      '/verify/email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verify/email-code/': RouteRecordInfo<
      '/verify/email-code/',
      '/verify/email-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verify/hard/': RouteRecordInfo<
      '/verify/hard/',
      '/verify/hard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verify/identity/': RouteRecordInfo<
      '/verify/identity/',
      '/verify/identity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verify/passport/': RouteRecordInfo<
      '/verify/passport/',
      '/verify/passport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verify/phone/': RouteRecordInfo<
      '/verify/phone/',
      '/verify/phone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verify/phone-code/': RouteRecordInfo<
      '/verify/phone-code/',
      '/verify/phone-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/welcome/': RouteRecordInfo<
      '/welcome/',
      '/welcome',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/conversation/[conversationSlugId]/edit/index.vue': {
      routes:
        | '/conversation/[conversationSlugId]/edit/'
      views:
        | never
    }
    'src/pages/conversation/[conversationSlugId]/edit/survey/index.vue': {
      routes:
        | '/conversation/[conversationSlugId]/edit/survey/'
      views:
        | never
    }
    'src/pages/conversation/[conversationSlugId]/export.vue': {
      routes:
        | '/conversation/[conversationSlugId]/export'
      views:
        | never
    }
    'src/pages/conversation/[conversationSlugId]/export.[exportId].vue': {
      routes:
        | '/conversation/[conversationSlugId]/export.[exportId]'
      views:
        | never
    }
    'src/pages/conversation/[conversationSlugId]/report.vue': {
      routes:
        | '/conversation/[conversationSlugId]/report'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].vue': {
      routes:
        | '/conversation/[postSlugId]'
        | '/conversation/[postSlugId]/'
        | '/conversation/[postSlugId]/analysis'
      views:
        | 'default'
    }
    'src/pages/conversation/[postSlugId]/index.vue': {
      routes:
        | '/conversation/[postSlugId]/'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId]/analysis.vue': {
      routes:
        | '/conversation/[postSlugId]/analysis'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].embed.vue': {
      routes:
        | '/conversation/[postSlugId].embed'
        | '/conversation/[postSlugId].embed/'
        | '/conversation/[postSlugId].embed/analysis'
      views:
        | 'default'
    }
    'src/pages/conversation/[postSlugId].embed/index.vue': {
      routes:
        | '/conversation/[postSlugId].embed/'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].embed/analysis.vue': {
      routes:
        | '/conversation/[postSlugId].embed/analysis'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding'
        | '/conversation/[postSlugId].onboarding/'
        | '/conversation/[postSlugId].onboarding/complete'
        | '/conversation/[postSlugId].onboarding/question.[questionSlugId]'
        | '/conversation/[postSlugId].onboarding/summary'
        | '/conversation/[postSlugId].onboarding/verify'
        | '/conversation/[postSlugId].onboarding/verify/email'
        | '/conversation/[postSlugId].onboarding/verify/email-code'
        | '/conversation/[postSlugId].onboarding/verify/hard'
        | '/conversation/[postSlugId].onboarding/verify/identity'
        | '/conversation/[postSlugId].onboarding/verify/passport'
        | '/conversation/[postSlugId].onboarding/verify/phone'
        | '/conversation/[postSlugId].onboarding/verify/phone-code'
        | '/conversation/[postSlugId].onboarding/verify/ticket'
      views:
        | 'default'
    }
    'src/pages/conversation/[postSlugId].onboarding/index.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/complete.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/complete'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/question.[questionSlugId].vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/question.[questionSlugId]'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/summary.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/summary'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/verify.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify'
        | '/conversation/[postSlugId].onboarding/verify/email'
        | '/conversation/[postSlugId].onboarding/verify/email-code'
        | '/conversation/[postSlugId].onboarding/verify/hard'
        | '/conversation/[postSlugId].onboarding/verify/identity'
        | '/conversation/[postSlugId].onboarding/verify/passport'
        | '/conversation/[postSlugId].onboarding/verify/phone'
        | '/conversation/[postSlugId].onboarding/verify/phone-code'
        | '/conversation/[postSlugId].onboarding/verify/ticket'
      views:
        | 'default'
    }
    'src/pages/conversation/[postSlugId].onboarding/verify/email.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify/email'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/verify/email-code.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify/email-code'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/verify/hard.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify/hard'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/verify/identity.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify/identity'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/verify/passport.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify/passport'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/verify/phone.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify/phone'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/verify/phone-code.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify/phone-code'
      views:
        | never
    }
    'src/pages/conversation/[postSlugId].onboarding/verify/ticket.vue': {
      routes:
        | '/conversation/[postSlugId].onboarding/verify/ticket'
      views:
        | never
    }
    'src/pages/conversation/import/[importSlugId].vue': {
      routes:
        | '/conversation/import/[importSlugId]'
      views:
        | never
    }
    'src/pages/conversation/new/create/index.vue': {
      routes:
        | '/conversation/new/create/'
      views:
        | never
    }
    'src/pages/conversation/new/review/index.vue': {
      routes:
        | '/conversation/new/review/'
      views:
        | never
    }
    'src/pages/conversation/new/seed/index.vue': {
      routes:
        | '/conversation/new/seed/'
      views:
        | never
    }
    'src/pages/conversation/new/survey/index.vue': {
      routes:
        | '/conversation/new/survey/'
      views:
        | never
    }
    'src/pages/dev/analysis-report-test.vue': {
      routes:
        | '/dev/analysis-report-test'
      views:
        | never
    }
    'src/pages/dev/component-testing.vue': {
      routes:
        | '/dev/component-testing'
      views:
        | never
    }
    'src/pages/dev/opinion-group-visualization.vue': {
      routes:
        | '/dev/opinion-group-visualization'
      views:
        | never
    }
    'src/pages/dev/test-components/AnalysisReportTest.vue': {
      routes:
        | '/dev/test-components/AnalysisReportTest'
      views:
        | never
    }
    'src/pages/dev/test-components/AsyncStateHandlerTest.vue': {
      routes:
        | '/dev/test-components/AsyncStateHandlerTest'
      views:
        | never
    }
    'src/pages/dev/test-components/EmbeddedBrowserWarningTest.vue': {
      routes:
        | '/dev/test-components/EmbeddedBrowserWarningTest'
      views:
        | never
    }
    'src/pages/dev/test-components/OpinionGroupVisualizationTest.vue': {
      routes:
        | '/dev/test-components/OpinionGroupVisualizationTest'
      views:
        | never
    }
    'src/pages/dev/test-components/PreferencesDialogTest.vue': {
      routes:
        | '/dev/test-components/PreferencesDialogTest'
      views:
        | never
    }
    'src/pages/legal/guidelines/index.vue': {
      routes:
        | '/legal/guidelines/'
      views:
        | never
    }
    'src/pages/legal/privacy/index.vue': {
      routes:
        | '/legal/privacy/'
      views:
        | never
    }
    'src/pages/legal/terms/index.vue': {
      routes:
        | '/legal/terms/'
      views:
        | never
    }
    'src/pages/moderate/conversation/[conversationSlugId]/index.vue': {
      routes:
        | '/moderate/conversation/[conversationSlugId]/'
      views:
        | never
    }
    'src/pages/moderate/conversation/[conversationSlugId]/opinion/[opinionSlugId]/index.vue': {
      routes:
        | '/moderate/conversation/[conversationSlugId]/opinion/[opinionSlugId]/'
      views:
        | never
    }
    'src/pages/notification/index.vue': {
      routes:
        | '/notification/'
      views:
        | never
    }
    'src/pages/onboarding/step1-login/index.vue': {
      routes:
        | '/onboarding/step1-login/'
      views:
        | never
    }
    'src/pages/onboarding/step1-signup/index.vue': {
      routes:
        | '/onboarding/step1-signup/'
      views:
        | never
    }
    'src/pages/onboarding/step2-signup/index.vue': {
      routes:
        | '/onboarding/step2-signup/'
      views:
        | never
    }
    'src/pages/onboarding/step3-email-1/index.vue': {
      routes:
        | '/onboarding/step3-email-1/'
      views:
        | never
    }
    'src/pages/onboarding/step3-email-2/index.vue': {
      routes:
        | '/onboarding/step3-email-2/'
      views:
        | never
    }
    'src/pages/onboarding/step3-passport/index.vue': {
      routes:
        | '/onboarding/step3-passport/'
      views:
        | never
    }
    'src/pages/onboarding/step3-phone-1/index.vue': {
      routes:
        | '/onboarding/step3-phone-1/'
      views:
        | never
    }
    'src/pages/onboarding/step3-phone-2/index.vue': {
      routes:
        | '/onboarding/step3-phone-2/'
      views:
        | never
    }
    'src/pages/onboarding/step4-username/index.vue': {
      routes:
        | '/onboarding/step4-username/'
      views:
        | never
    }
    'src/pages/reports/[reportType]/[conversationSlugId]/[[opinionSlugId]].vue': {
      routes:
        | '/reports/[reportType]/[conversationSlugId]/[[opinionSlugId]]'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/account/administrator/organization/index.vue': {
      routes:
        | '/settings/account/administrator/organization/'
      views:
        | never
    }
    'src/pages/settings/account/content-preference/index.vue': {
      routes:
        | '/settings/account/content-preference/'
      views:
        | never
    }
    'src/pages/settings/account/profile/index.vue': {
      routes:
        | '/settings/account/profile/'
      views:
        | never
    }
    'src/pages/settings/languages/index.vue': {
      routes:
        | '/settings/languages/'
      views:
        | never
    }
    'src/pages/settings/languages/display-language/index.vue': {
      routes:
        | '/settings/languages/display-language/'
      views:
        | never
    }
    'src/pages/settings/languages/spoken-languages/index.vue': {
      routes:
        | '/settings/languages/spoken-languages/'
      views:
        | never
    }
    'src/pages/settings/verification-status/index.vue': {
      routes:
        | '/settings/verification-status/'
      views:
        | never
    }
    'src/pages/topic/[topicCode].vue': {
      routes:
        | '/topic/[topicCode]'
      views:
        | never
    }
    'src/pages/topics/index.vue': {
      routes:
        | '/topics/'
      views:
        | never
    }
    'src/pages/user-profile.vue': {
      routes:
        | '/user-profile'
        | '/user-profile/conversations/'
        | '/user-profile/opinions/'
      views:
        | 'default'
    }
    'src/pages/user-profile/conversations/index.vue': {
      routes:
        | '/user-profile/conversations/'
      views:
        | never
    }
    'src/pages/user-profile/opinions/index.vue': {
      routes:
        | '/user-profile/opinions/'
      views:
        | never
    }
    'src/pages/verify/email/index.vue': {
      routes:
        | '/verify/email/'
      views:
        | never
    }
    'src/pages/verify/email-code/index.vue': {
      routes:
        | '/verify/email-code/'
      views:
        | never
    }
    'src/pages/verify/hard/index.vue': {
      routes:
        | '/verify/hard/'
      views:
        | never
    }
    'src/pages/verify/identity/index.vue': {
      routes:
        | '/verify/identity/'
      views:
        | never
    }
    'src/pages/verify/passport/index.vue': {
      routes:
        | '/verify/passport/'
      views:
        | never
    }
    'src/pages/verify/phone/index.vue': {
      routes:
        | '/verify/phone/'
      views:
        | never
    }
    'src/pages/verify/phone-code/index.vue': {
      routes:
        | '/verify/phone-code/'
      views:
        | never
    }
    'src/pages/welcome/index.vue': {
      routes:
        | '/welcome/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
