from typing import Self

class DockerContainer:
    def __init__(self, image: str) -> None: ...
    def with_exposed_ports(self, *ports: int) -> Self: ...
    def waiting_for(self, strategy: object) -> Self: ...
    def start(self) -> Self: ...
    def stop(self) -> None: ...
    def get_container_host_ip(self) -> str: ...
    def get_exposed_port(self, port: int) -> str: ...
