from collections.abc import Iterable, Iterator
from typing import Any, overload

class Index[T]:
    def __init__(self, data: Iterable[T], *, name: str | None = None) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, index: int) -> T: ...
    @overload
    def __getitem__(self, index: slice) -> list[T]: ...

class Series[T]:
    def __getitem__(self, key: Any) -> T: ...
    def unique(self) -> list[T]: ...

class DataFrame:
    columns: Index[Any]
    index: Index[Any]
    empty: bool

    def __init__(
        self,
        data: Any = ...,
        *,
        index: Index[Any] | None = ...,
        columns: Index[Any] | None = ...,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: str) -> Series[Any]: ...
    def assign(self, **kwargs: Any) -> DataFrame: ...
    def to_dict(self, orient: str = ...) -> Any: ...
