import type { SupportedDisplayLanguageCodes } from "src/shared/languages";

export interface AdministratorOrganizationApiTranslations {
  failedToFetchOrganizations: string;
  addedUserOrganizationMapping: string;
  failedToAddUserOrganizationMapping: string;
  removedUserOrganizationMapping: string;
  failedToRemoveUserOrganizationMapping: string;
  deletedOrganization: string;
  failedToDeleteOrganization: string;
  createdUserOrganization: string;
  failedToCreateUserOrganization: string;
  failedToGetUserOrganizations: string;
}

export const administratorOrganizationApiTranslations: Record<
  SupportedDisplayLanguageCodes,
  AdministratorOrganizationApiTranslations
> = {
  en: { failedToFetchOrganizations: "Failed to fetch organizations", addedUserOrganizationMapping: "Added user organization mapping", failedToAddUserOrganizationMapping: "Failed to add user organization mapping", removedUserOrganizationMapping: "Removed user organization mapping", failedToRemoveUserOrganizationMapping: "Failed to remove user organization mapping", deletedOrganization: "Deleted organization", failedToDeleteOrganization: "Failed to delete organization", createdUserOrganization: "Created user organization", failedToCreateUserOrganization: "Failed to create user organization", failedToGetUserOrganizations: "Failed to get user's organizations" },
  es: { failedToFetchOrganizations: "No se pudieron obtener las organizaciones", addedUserOrganizationMapping: "Asignación usuario-organización agregada", failedToAddUserOrganizationMapping: "No se pudo agregar la asignación usuario-organización", removedUserOrganizationMapping: "Asignación usuario-organización eliminada", failedToRemoveUserOrganizationMapping: "No se pudo eliminar la asignación usuario-organización", deletedOrganization: "Organización eliminada", failedToDeleteOrganization: "No se pudo eliminar la organización", createdUserOrganization: "Organización de usuario creada", failedToCreateUserOrganization: "No se pudo crear la organización de usuario", failedToGetUserOrganizations: "No se pudieron obtener las organizaciones del usuario" },
  fr: { failedToFetchOrganizations: "Échec de la récupération des organisations", addedUserOrganizationMapping: "Association utilisateur-organisation ajoutée", failedToAddUserOrganizationMapping: "Échec de l’ajout de l’association utilisateur-organisation", removedUserOrganizationMapping: "Association utilisateur-organisation supprimée", failedToRemoveUserOrganizationMapping: "Échec de la suppression de l’association utilisateur-organisation", deletedOrganization: "Organisation supprimée", failedToDeleteOrganization: "Échec de la suppression de l’organisation", createdUserOrganization: "Organisation utilisateur créée", failedToCreateUserOrganization: "Échec de la création de l’organisation utilisateur", failedToGetUserOrganizations: "Échec de la récupération des organisations de l’utilisateur" },
  "zh-Hant": { failedToFetchOrganizations: "取得組織失敗", addedUserOrganizationMapping: "已新增使用者組織對應", failedToAddUserOrganizationMapping: "新增使用者組織對應失敗", removedUserOrganizationMapping: "已移除使用者組織對應", failedToRemoveUserOrganizationMapping: "移除使用者組織對應失敗", deletedOrganization: "組織已刪除", failedToDeleteOrganization: "刪除組織失敗", createdUserOrganization: "使用者組織已建立", failedToCreateUserOrganization: "建立使用者組織失敗", failedToGetUserOrganizations: "取得使用者組織失敗" },
  "zh-Hans": { failedToFetchOrganizations: "获取组织失败", addedUserOrganizationMapping: "已添加用户组织映射", failedToAddUserOrganizationMapping: "添加用户组织映射失败", removedUserOrganizationMapping: "已移除用户组织映射", failedToRemoveUserOrganizationMapping: "移除用户组织映射失败", deletedOrganization: "组织已删除", failedToDeleteOrganization: "删除组织失败", createdUserOrganization: "用户组织已创建", failedToCreateUserOrganization: "创建用户组织失败", failedToGetUserOrganizations: "获取用户组织失败" },
  ja: { failedToFetchOrganizations: "組織を取得できませんでした", addedUserOrganizationMapping: "ユーザーと組織の関連付けを追加しました", failedToAddUserOrganizationMapping: "ユーザーと組織の関連付けを追加できませんでした", removedUserOrganizationMapping: "ユーザーと組織の関連付けを削除しました", failedToRemoveUserOrganizationMapping: "ユーザーと組織の関連付けを削除できませんでした", deletedOrganization: "組織を削除しました", failedToDeleteOrganization: "組織を削除できませんでした", createdUserOrganization: "ユーザー組織を作成しました", failedToCreateUserOrganization: "ユーザー組織を作成できませんでした", failedToGetUserOrganizations: "ユーザーの組織を取得できませんでした" },
  ar: { failedToFetchOrganizations: "فشل جلب المؤسسات", addedUserOrganizationMapping: "تمت إضافة ربط المستخدم بالمؤسسة", failedToAddUserOrganizationMapping: "فشل إضافة ربط المستخدم بالمؤسسة", removedUserOrganizationMapping: "تمت إزالة ربط المستخدم بالمؤسسة", failedToRemoveUserOrganizationMapping: "فشل إزالة ربط المستخدم بالمؤسسة", deletedOrganization: "تم حذف المؤسسة", failedToDeleteOrganization: "فشل حذف المؤسسة", createdUserOrganization: "تم إنشاء مؤسسة المستخدم", failedToCreateUserOrganization: "فشل إنشاء مؤسسة المستخدم", failedToGetUserOrganizations: "فشل جلب مؤسسات المستخدم" },
  fa: { failedToFetchOrganizations: "دریافت سازمان‌ها ناموفق بود", addedUserOrganizationMapping: "نگاشت کاربر به سازمان افزوده شد", failedToAddUserOrganizationMapping: "افزودن نگاشت کاربر به سازمان ناموفق بود", removedUserOrganizationMapping: "نگاشت کاربر به سازمان حذف شد", failedToRemoveUserOrganizationMapping: "حذف نگاشت کاربر به سازمان ناموفق بود", deletedOrganization: "سازمان حذف شد", failedToDeleteOrganization: "حذف سازمان ناموفق بود", createdUserOrganization: "سازمان کاربر ایجاد شد", failedToCreateUserOrganization: "ایجاد سازمان کاربر ناموفق بود", failedToGetUserOrganizations: "دریافت سازمان‌های کاربر ناموفق بود" },
  he: { failedToFetchOrganizations: "טעינת הארגונים נכשלה", addedUserOrganizationMapping: "שיוך המשתמש לארגון נוסף", failedToAddUserOrganizationMapping: "הוספת שיוך המשתמש לארגון נכשלה", removedUserOrganizationMapping: "שיוך המשתמש לארגון הוסר", failedToRemoveUserOrganizationMapping: "הסרת שיוך המשתמש לארגון נכשלה", deletedOrganization: "הארגון נמחק", failedToDeleteOrganization: "מחיקת הארגון נכשלה", createdUserOrganization: "ארגון המשתמש נוצר", failedToCreateUserOrganization: "יצירת ארגון המשתמש נכשלה", failedToGetUserOrganizations: "טעינת הארגונים של המשתמש נכשלה" },
  ky: { failedToFetchOrganizations: "Уюмдарды алуу ишке ашкан жок", addedUserOrganizationMapping: "Колдонуучу-уюм байланышы кошулду", failedToAddUserOrganizationMapping: "Колдонуучу-уюм байланышын кошуу ишке ашкан жок", removedUserOrganizationMapping: "Колдонуучу-уюм байланышы өчүрүлдү", failedToRemoveUserOrganizationMapping: "Колдонуучу-уюм байланышын өчүрүү ишке ашкан жок", deletedOrganization: "Уюм өчүрүлдү", failedToDeleteOrganization: "Уюмду өчүрүү ишке ашкан жок", createdUserOrganization: "Колдонуучу уюму түзүлдү", failedToCreateUserOrganization: "Колдонуучу уюмун түзүү ишке ашкан жок", failedToGetUserOrganizations: "Колдонуучунун уюмдарын алуу ишке ашкан жок" },
  ru: { failedToFetchOrganizations: "Не удалось получить организации", addedUserOrganizationMapping: "Связь пользователя с организацией добавлена", failedToAddUserOrganizationMapping: "Не удалось добавить связь пользователя с организацией", removedUserOrganizationMapping: "Связь пользователя с организацией удалена", failedToRemoveUserOrganizationMapping: "Не удалось удалить связь пользователя с организацией", deletedOrganization: "Организация удалена", failedToDeleteOrganization: "Не удалось удалить организацию", createdUserOrganization: "Организация пользователя создана", failedToCreateUserOrganization: "Не удалось создать организацию пользователя", failedToGetUserOrganizations: "Не удалось получить организации пользователя" },
};
