version: "3.8"

# when connecting to the database from pgadmin,
# use `docker container ls`, the identify postgres's ID, then
# `docker inspect <id>` then copy `"IPAddress": "some.ip.address.toCopy"`
# paste the ip address in `hostname` in pgadmin when connecting to the server
#
#
# Follow that guide https://aws.amazon.com/blogs/database/managing-postgresql-users-and-roles/
# create a prisma user with superuser privilege - use this one for the prisma commands
# create an app user with readwrite role - use this one for the app
# create an appread user with readonly role - use this one to inspect the DB locally

services:
    postgres:
        container_name: postgres_container
        image: postgres:16
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 7QPgtYETx4EdzvqUeNfo
            POSTGRES_DB: agora
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
            - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        ports:
            - "5432:5432"
        restart: always
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: UsXWq98V68DxGEhfGvBa
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        restart: always

volumes:
    postgres:
    pgadmin:
