minimumReleaseAge: 7200
minimumReleaseAgeExclude:
    - "@zkorum/lingua-wasm@1.8.0"

ignoredBuiltDependencies:
    - protobufjs

onlyBuiltDependencies:
    - esbuild

patchedDependencies:
    "@zk-kit/eddsa-poseidon@1.1.0": patches/@zk-kit__eddsa-poseidon@1.1.0.patch
