ignoredBuiltDependencies:
  - protobufjs

onlyBuiltDependencies:
  - esbuild
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'

patchedDependencies:
  '@zk-kit/eddsa-poseidon@1.1.0': patches/@zk-kit__eddsa-poseidon@1.1.0.patch
