version: "3.8"
services:
  postgres:
    container_name: agora_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CHANGEME
      POSTGRES_DB: agora
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./services/back/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    expose:
      - "5432"
    restart: unless-stopped
  pgadmin:
    container_name: agora_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zkorum.com
      PGADMIN_DEFAULT_PASSWORD: CHANGEME
    volumes:
      - pgadmin:/var/lib/pgadmin
    expose:
      - "80"
    restart: unless-stopped
  api:
    container_name: agora_api
    image: zkorum/agora-api:0.1.26
    environment:
      CONNECTION_STRING: "postgres://postgres:CHANGEME@postgres:5432/agora"
      CORS_ORIGIN_LIST: "http://localhost:9000,http://127.0.0.1:9000,http://172.19.0.1:9000,http://192.168.1.22:9000"
      PEPPERS: "fmgXvsChQsx9fAlq0DPiVg=="
      NODE_ENV: "production"
      VERIFICATOR_SVC_BASE_URL: "http://verificator-svc:8000"
    expose:
      - "8080"
    restart: unless-stopped
  verificator-svc:
    container_name: verificator_svc
    image: zkorum/verificator-svc:0.2.2
    command: run service
    environment:
      KV_VIPER_FILE: "/config/config.yaml"
    volumes: 
      - ./script/rarimo/config:/config
    expose:
      - "8000"
    restart: unless-stopped
  agora:
    container_name: agora_app
    image: zkorum/agora-app:0.1.0
    expose:
      - "80"
    restart: unless-stopped
  nginx:
    image: nginx:stable-alpine
    container_name: agora_nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 5050:5050
    volumes:
      - ./vhosts:/etc/nginx/conf.d
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email admin@zkorum.com --agree-tos --no-eff-email -d agoracitizen.network
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/logs:/var/log/letsencrypt

volumes:
  postgres:
  pgadmin:
