from testcontainers.core.container import DockerContainer

class PostgresContainer(DockerContainer):
    def __init__(self, image: str, *, driver: str) -> None: ...
    def get_connection_url(self) -> str: ...
