ALTER TABLE "conversation_email_update_conversation" ADD COLUMN "conversation_url_snapshot" text;--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD COLUMN "cancelled_at" timestamp (0);--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD COLUMN "review_expires_at" timestamp (0);--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD COLUMN "template_version" varchar(100);--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD COLUMN "participant_preference_scope_snapshot" "conversation_email_update_participant_preference_scope";--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD COLUMN "branding_snapshot" jsonb;--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD COLUMN "review_test_email_credential_id" integer;--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD COLUMN "review_test_email_snapshot" varchar(254);--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD CONSTRAINT "email_update_review_test_destination_owner_fk" FOREIGN KEY ("created_by_user_id","review_test_email_credential_id") REFERENCES "public"."email"("user_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "conversation_email_update_creator_created_idx" ON "conversation_email_update" USING btree ("created_by_user_id","created_at");--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD CONSTRAINT "conversation_email_update_review_fields_check" CHECK (num_nonnulls("conversation_email_update"."review_expires_at", "conversation_email_update"."template_version", "conversation_email_update"."participant_preference_scope_snapshot", "conversation_email_update"."branding_snapshot", "conversation_email_update"."review_test_email_credential_id", "conversation_email_update"."review_test_email_snapshot") IN (0, 6) AND ("conversation_email_update"."cancelled_at" IS NULL OR "conversation_email_update"."review_expires_at" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD CONSTRAINT "conversation_email_update_review_expiry_check" CHECK ("conversation_email_update"."review_expires_at" IS NULL OR ("conversation_email_update"."review_expires_at" = "conversation_email_update"."created_at" + interval '24 hours' AND length(btrim("conversation_email_update"."template_version")) > 0));--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD CONSTRAINT "conversation_email_update_review_scope_check" CHECK ("conversation_email_update"."scope_kind" <> 'no_project' OR "conversation_email_update"."participant_preference_scope_snapshot" IS NULL OR "conversation_email_update"."participant_preference_scope_snapshot" = 'conversation');--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD CONSTRAINT "conversation_email_update_branding_check" CHECK ("conversation_email_update"."branding_snapshot" IS NULL OR (jsonb_typeof("conversation_email_update"."branding_snapshot") = 'object' AND "conversation_email_update"."branding_snapshot" ?& array['name', 'palette'] AND jsonb_typeof("conversation_email_update"."branding_snapshot"->'name') = 'string' AND length(btrim("conversation_email_update"."branding_snapshot"->>'name')) BETWEEN 1 AND 500 AND jsonb_typeof("conversation_email_update"."branding_snapshot"->'palette') = 'string' AND "conversation_email_update"."branding_snapshot"->>'palette' IN ('blue', 'purple', 'green') AND (NOT "conversation_email_update"."branding_snapshot" ? 'imageUrl' OR jsonb_typeof("conversation_email_update"."branding_snapshot"->'imageUrl') = 'string') AND (NOT "conversation_email_update"."branding_snapshot" ? 'bannerImageUrl' OR jsonb_typeof("conversation_email_update"."branding_snapshot"->'bannerImageUrl') = 'string')));--> statement-breakpoint
ALTER TABLE "conversation_email_update" ADD CONSTRAINT "conversation_email_update_review_test_email_canonical_check" CHECK ("conversation_email_update"."review_test_email_snapshot" IS NULL OR (length(btrim("conversation_email_update"."review_test_email_snapshot")) > 0 AND "conversation_email_update"."review_test_email_snapshot" = lower(btrim("conversation_email_update"."review_test_email_snapshot"))));