# build environment
FROM node:22-alpine AS build
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH
COPY . ./
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm run build:production

# production environment
FROM nginx:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/spa /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
