minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - launder@1.7.1

allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': false
  browser-tabs-lock: false
  core-js: false
  esbuild: false
  vue-demi: false

peerDependencyRules:
  allowedVersions:
    '@commander-js/extra-typings>commander': '14'

overrides:
  'eslint>ajv': '^6.14.0'
  '@eslint/eslintrc>ajv': '^6.14.0'
  '@stablelib/ed25519': '2.1.0'
  hono: '4.12.18'
  ip-address: '10.1.1'
  circom_tester: '0.0.24'
  yaml: '2.8.3'
  bn.js: '5.2.3'
  picomatch: '4.0.4'
  jsonpath: '1.3.0'
  underscore: '1.13.8'
