/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/help/': RouteRecordInfo<'/help/', '/help', Record<never, never>, Record<never, never>>,
    '/legal/privacy/': RouteRecordInfo<'/legal/privacy/', '/legal/privacy', Record<never, never>, Record<never, never>>,
    '/legal/terms/': RouteRecordInfo<'/legal/terms/', '/legal/terms', Record<never, never>, Record<never, never>>,
    '/moderate/comment/[commentSlugId]/': RouteRecordInfo<'/moderate/comment/[commentSlugId]/', '/moderate/comment/:commentSlugId', { commentSlugId: ParamValue<true> }, { commentSlugId: ParamValue<false> }>,
    '/moderate/post/[postSlugId]/': RouteRecordInfo<'/moderate/post/[postSlugId]/', '/moderate/post/:postSlugId', { postSlugId: ParamValue<true> }, { postSlugId: ParamValue<false> }>,
    '/onboarding/step1-login/': RouteRecordInfo<'/onboarding/step1-login/', '/onboarding/step1-login', Record<never, never>, Record<never, never>>,
    '/onboarding/step1-signup/': RouteRecordInfo<'/onboarding/step1-signup/', '/onboarding/step1-signup', Record<never, never>, Record<never, never>>,
    '/onboarding/step2-signup/': RouteRecordInfo<'/onboarding/step2-signup/', '/onboarding/step2-signup', Record<never, never>, Record<never, never>>,
    '/onboarding/step3-passport/': RouteRecordInfo<'/onboarding/step3-passport/', '/onboarding/step3-passport', Record<never, never>, Record<never, never>>,
    '/onboarding/step3-phone-1/': RouteRecordInfo<'/onboarding/step3-phone-1/', '/onboarding/step3-phone-1', Record<never, never>, Record<never, never>>,
    '/onboarding/step3-phone-2/': RouteRecordInfo<'/onboarding/step3-phone-2/', '/onboarding/step3-phone-2', Record<never, never>, Record<never, never>>,
    '/onboarding/step4-username/': RouteRecordInfo<'/onboarding/step4-username/', '/onboarding/step4-username', Record<never, never>, Record<never, never>>,
    '/onboarding/step5-experience-deprecated/': RouteRecordInfo<'/onboarding/step5-experience-deprecated/', '/onboarding/step5-experience-deprecated', Record<never, never>, Record<never, never>>,
    '/onboarding/step5-preferences/': RouteRecordInfo<'/onboarding/step5-preferences/', '/onboarding/step5-preferences', Record<never, never>, Record<never, never>>,
    '/post/[postSlugId]': RouteRecordInfo<'/post/[postSlugId]', '/post/:postSlugId', { postSlugId: ParamValue<true> }, { postSlugId: ParamValue<false> }>,
    '/post/create/': RouteRecordInfo<'/post/create/', '/post/create', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/account/muted-users/': RouteRecordInfo<'/settings/account/muted-users/', '/settings/account/muted-users', Record<never, never>, Record<never, never>>,
    '/settings/account/profile/': RouteRecordInfo<'/settings/account/profile/', '/settings/account/profile', Record<never, never>, Record<never, never>>,
    '/user-profile': RouteRecordInfo<'/user-profile', '/user-profile', Record<never, never>, Record<never, never>>,
    '/user-profile/comments/': RouteRecordInfo<'/user-profile/comments/', '/user-profile/comments', Record<never, never>, Record<never, never>>,
    '/user-profile/posts/': RouteRecordInfo<'/user-profile/posts/', '/user-profile/posts', Record<never, never>, Record<never, never>>,
    '/user-reports/[reportType]/[slugId]/': RouteRecordInfo<'/user-reports/[reportType]/[slugId]/', '/user-reports/:reportType/:slugId', { reportType: ParamValue<true>, slugId: ParamValue<true> }, { reportType: ParamValue<false>, slugId: ParamValue<false> }>,
    '/welcome/': RouteRecordInfo<'/welcome/', '/welcome', Record<never, never>, Record<never, never>>,
  }
}
