from typing import Any

class Valkey:
    def __init__(self, *, host: str, port: int, decode_responses: bool = ...) -> None: ...
    def ping(self) -> bool: ...
    def zadd(self, key: str, mapping: dict[str, int | float]) -> int: ...
    def zpopmin(self, key: str, count: int = ...) -> list[tuple[str, float]]: ...
    def zcard(self, key: str) -> int: ...
    def flushall(self) -> Any: ...
    def close(self) -> None: ...

def from_url(url: str, *, decode_responses: bool = ...) -> Valkey: ...
