import {
    DEFAULT_FEATURE_ALLOWED_ORGS,
    DEFAULT_FEATURE_ALLOWED_USERS,
} from "./featureAccess.js";

export const DEFAULT_MAXDIFF_GITHUB_ALLOWED_ORGS = DEFAULT_FEATURE_ALLOWED_ORGS;
export const DEFAULT_MAXDIFF_GITHUB_ALLOWED_USERS = DEFAULT_FEATURE_ALLOWED_USERS;
