# generated by datamodel-codegen:
#   filename:  agora-import-worker-contract.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class ParticipationMode(StrEnum):
    account_required = "account_required"
    strong_verification = "strong_verification"
    email_verification = "email_verification"
    guest = "guest"


class RequiresEventTicket(StrEnum):
    devconnect_2025 = "devconnect-2025"


class ImportFormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    post_as_organization: str | None = Field(None, alias="postAsOrganization")
    participation_mode: ParticipationMode = Field(..., alias="participationMode")
    is_indexed: bool = Field(..., alias="isIndexed")
    requires_event_ticket: RequiresEventTicket | None = Field(None, alias="requiresEventTicket")
    ai_labeling_enabled: bool = Field(True, alias="aiLabelingEnabled")


class CsvFiles(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    summary_file: str = Field(..., alias="summaryFile")
    comments_file: str = Field(..., alias="commentsFile")
    votes_file: str = Field(..., alias="votesFile")


class UrlImportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    import_slug_id: str = Field(..., alias="importSlugId")
    user_id: str = Field(..., alias="userId")
    form_data: ImportFormData = Field(..., alias="formData")
    did_write: str = Field(..., alias="didWrite")
    author_id: str = Field(..., alias="authorId")
    type: Literal["url"]
    polis_url: str = Field(..., alias="polisUrl")


class MinimalImportRequest(BaseModel):
    model_config = ConfigDict(
        validate_by_name=True,
    )
    import_slug_id: str = Field(..., alias="importSlugId")
    user_id: str = Field(..., alias="userId")


class ImportWorkerEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    type: Literal["import_notification"]
    user_id: str = Field(..., alias="userId")
    notification_slug_id: str = Field(..., alias="notificationSlugId")
    import_id: int = Field(..., alias="importId")
    conversation_id: int | None = Field(..., alias="conversationId")
    broadcast_new_conversation: bool = Field(False, alias="broadcastNewConversation")


class CsvImportRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    import_slug_id: str = Field(..., alias="importSlugId")
    user_id: str = Field(..., alias="userId")
    form_data: ImportFormData = Field(..., alias="formData")
    did_write: str = Field(..., alias="didWrite")
    author_id: str = Field(..., alias="authorId")
    type: Literal["csv"]
    files: CsvFiles


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        validate_by_name=True,
    )
    import_request: CsvImportRequest | UrlImportRequest = Field(..., alias="importRequest")
    minimal_import_request: MinimalImportRequest = Field(..., alias="minimalImportRequest")
    import_worker_event: ImportWorkerEvent = Field(..., alias="importWorkerEvent")
